#!/usr/bin/env python3
"""Private season-state tracker: which leagues show LAST season's final table
versus a projection for the NEW one.

Not a public artifact. Writes to output/ (gitignored) and prints to stdout —
nothing here reaches webapp/.

Why this exists
---------------
A league's status is not a calendar decision, it is a *fixture-feed* decision.
scripts/eval/season_state.py classifies purely on match counts:

    played=0, upcoming>0  -> preseason     (projecting the new season)
    played>0, upcoming>0  -> live
    played>0, upcoming=0  -> completed     (final table of the season just gone)

So a league parks on "completed" — showing a dead final table — from its last
match until the day its source publishes next season's schedule. That gap is
invisible: nothing alerts, and the weekly rebuild happily reproduces the same
stale table. This report makes the gap visible and ranks it by how long the
league has been sitting there.

Usage:
    python3 scripts/season_state_report.py                # table + write report
    python3 scripts/season_state_report.py --stale-days 30
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "webapp" / "data"
OUT = ROOT / "output" / "season-state.md"

# Liga MX stores a sequential torneo id (Clausura 2017 = 1 ... Apertura 2026 = 20)
# rather than a year, so the raw `season` int is meaningless on its own. Every
# payload that has one carries a human label in outlook.season_label; prefer it.
SHOWS = {
    "preseason": "projection — new season",
    "live": "projection — season underway",
    "completed": "FINAL TABLE — season over",
    "knockout_live": "projection — knockout underway",
}


def _load(p: Path):
    m = re.match(r"window\.\w+\s*=\s*(.*?);?\s*$", p.read_text(encoding="utf-8"), re.DOTALL)
    return json.loads(m.group(1)) if m else None


def _registry() -> dict[str, dict]:
    reg = _load(ROOT / "webapp" / "leagues.js") or []
    return {r["id"]: r for r in reg}


def _last_result_date(payload: dict) -> date | None:
    """Newest date among matches that actually have a result."""
    best = None
    for g in payload.get("games") or []:
        if g.get("result") is None and g.get("hg") is None:
            continue
        d = g.get("date")
        if not d:
            continue
        try:
            dt = datetime.strptime(d[:10], "%Y-%m-%d").date()
        except ValueError:
            continue
        if best is None or dt > best:
            best = dt
    return best


def collect(today: date) -> list[dict]:
    reg = _registry()
    rows = []
    for p in sorted(DATA.glob("*.js")):
        lid = p.stem
        if lid not in reg:            # cross-league artifacts (power, drift, ledger…)
            continue
        try:
            d = _load(p)
        except Exception:
            continue
        if not isinstance(d, dict) or "status" not in d:
            continue
        last = _last_result_date(d)
        outlook = d.get("outlook") or {}
        rows.append({
            "id": lid,
            "name": reg[lid].get("name", lid),
            "country": reg[lid].get("country") or "",
            "status": d.get("status"),
            "shows": SHOWS.get(d.get("status"), d.get("status")),
            "season": outlook.get("season_label") or d.get("season"),
            "played": d.get("played"),
            # `upcoming` is a fixture LIST in most payloads but a plain count in
            # some (MLS-mode builders emit the number) — accept either.
            "upcoming": (len(u) if isinstance(u := d.get("upcoming") or [], list) else int(u)),
            "last_result": last,
            "days_since": (today - last).days if last else None,
            "generated": d.get("generated"),
        })
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stale-days", type=int, default=45,
                    help="a 'completed' league idle this long is flagged for rollover")
    args = ap.parse_args()

    today = date.today()
    rows = collect(today)
    done = [r for r in rows if r["status"] == "completed"]
    stale = sorted((r for r in done if (r["days_since"] or 0) >= args.stale_days),
                   key=lambda r: -(r["days_since"] or 0))
    recent = sorted((r for r in done if (r["days_since"] or 0) < args.stale_days),
                    key=lambda r: -(r["days_since"] or 0))

    lines = [
        f"# Season-state tracker — {today.isoformat()}",
        "",
        "Private. Generated by `scripts/season_state_report.py`; `output/` is gitignored.",
        "",
        f"- **{sum(1 for r in rows if r['status'] == 'preseason')}** leagues projecting a new season (preseason)",
        f"- **{sum(1 for r in rows if r['status'] in ('live', 'knockout_live'))}** leagues in season",
        f"- **{len(done)}** leagues showing a FINAL TABLE from the season just gone",
        f"  - of those, **{len(stale)}** have been idle ≥ {args.stale_days} days",
        "",
        "A league flips off `completed` only when its source publishes the next",
        "schedule — status is derived from fixture counts, never from the calendar",
        "(`scripts/eval/season_state.py`). Everything in the first table below is",
        "therefore waiting on a fixture feed, not on a code change.",
        "",
        f"## Showing a dead final table, idle ≥ {args.stale_days} days",
        "",
        "| League | Country | Season shown | Last result | Days idle |",
        "|---|---|---|---:|---:|",
    ]
    for r in stale:
        lines.append(f"| {r['name']} | {r['country']} | {r['season']} | "
                     f"{r['last_result']} | {r['days_since']} |")
    if not stale:
        lines.append("| _none_ | | | | |")

    # Second failure mode, and the nastier one: a league still labelled live or
    # preseason that has not played in months. "Completed" at least tells the
    # reader the table is final; a stale "live" badge actively claims the
    # projection is current when it is not.
    idle_live = sorted(
        (r for r in rows
         if r["status"] in ("live", "preseason", "knockout_live")
         and (r["days_since"] or 0) >= args.stale_days),
        key=lambda r: -(r["days_since"] or 0))
    lines += ["", f"## Labelled in-season but idle ≥ {args.stale_days} days", "",
              "These claim a current projection while the fixture feed has gone",
              "quiet — either a genuine mid-season break, or a season that ended",
              "without the feed closing it out. Check each against the real calendar.",
              "",
              "| League | Country | Status | Season shown | Last result | Days idle |",
              "|---|---|---|---|---:|---:|"]
    for r in idle_live:
        lines.append(f"| {r['name']} | {r['country']} | {r['status']} | {r['season']} | "
                     f"{r['last_result']} | {r['days_since']} |")
    if not idle_live:
        lines.append("| _none_ | | | | | |")

    lines += ["", "## Recently concluded (rollover not yet due)", "",
              "| League | Country | Season shown | Last result | Days idle |",
              "|---|---|---:|---:|---:|"]
    for r in recent:
        lines.append(f"| {r['name']} | {r['country']} | {r['season']} | "
                     f"{r['last_result']} | {r['days_since']} |")
    if not recent:
        lines.append("| _none_ | | | | |")

    lines += ["", "## Full state", "",
              "| League | Country | Site shows | Season | Played | Upcoming | Last result |",
              "|---|---|---|---|---:|---:|---:|"]
    for r in sorted(rows, key=lambda r: (r["status"] or "", r["name"])):
        lines.append(f"| {r['name']} | {r['country']} | {r['shows']} | {r['season']} | "
                     f"{r['played']} | {r['upcoming']} | {r['last_result']} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"{'league':30} {'country':16} {'shows':30} {'season':9} idle")
    print("-" * 95)
    for r in sorted(rows, key=lambda r: (r["status"] != "completed",
                                         -(r["days_since"] or 0))):
        idle = (r["days_since"] or 0) >= args.stale_days
        flag = ("  <-- ROLL OVER" if r["status"] == "completed" and idle
                else "  <-- STALE 'LIVE'" if idle else "")
        print(f"{r['name'][:30]:30} {r['country'][:16]:16} {r['shows'][:30]:30} "
              f"{str(r['season'])[:9]:9} {str(r['days_since']):>4}{flag}")
    print(f"\n{len(stale)} league(s) idle >= {args.stale_days} days. Report: {OUT}")


if __name__ == "__main__":
    main()
